<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="/css/main.css" charset="utf-8">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<body>
<?php include 'message.inc'; ?>
<div class="container">

  <div class="row">
    <div class="col-md-6">

      <div class="btn-group" role="group">
        <a class="btn btn-default" href="/">Home</a>
        <a class="btn btn-default" href="/photos">All photos</a>
        <a class="btn btn-default" href="/photo/new">New photo</a>
      </div>

    </div>
  </div>

</div>
